# Generated by Django 4.2.4 on 2023-09-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
