# Generated by Django 4.2.4 on 2023-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
