# Generated by Django 4.2.4 on 2023-09-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total_amount_productinorder_nmb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
    ]
