# Generated by Django 4.2.4 on 2023-09-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_total_amount_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда в заказе'},
        ),
    ]
