# Generated by Django 4.2.4 on 2023-09-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='session_key',
        ),
    ]
