# Generated by Django 4.2.4 on 2023-09-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_productinbasket_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='order',
        ),
    ]
